### PR TITLE
Beta

### PR DESCRIPTION
**Pull request by niklasp**
I am adding a new iteration for the stake and vote kusamarian app as contracted with Jay. Please review. It's still a wip but staking + delgating works. see readme on how to run or this live url

https://thekusamarian.github.io/stake-n-vote/

It also includes next.js as a build tool and a ci pipeline for github builds + github pages for hosting

### CODE REVIEW

**Review by kirushik — CHANGES_REQUESTED** [review]
@niklasp haven't reviewed the attached code yet, but what catches my attention is that it introduces both Github Pages and Vercel deployments, while ignoring the existing Cloudflare Pages ones.
What's worse is that when deploying to Github Pages it doesn't deploy to a branch-specific namespace (is it even possible with Pages?), and just overwrites the main repo's pages.
This means that a) we can't be working on two PRs in parallel, since there's no way to tell which one will be deployed last; and b) we don't have any separation between the work-in-progress PR deployment and the final production one.

My current Cloudflare pages setup just runs `yarn build` after installing the dependencies, and publishes the contents of the resulting `/dist` folder to a branch-specific subdomain.
Can you please update your setup to remove all other ways of doing deployments, and make your build compliant with that system?
Should be pretty trivial to do by just altering `package.json`.

**Comment by kirushik** [comment]
@niklasp  On a bit of a more substantive note, what's the rationale between replacing Parcel with NextJS?
I understand that you might have personal preferences for React over my minimalistic `lit`+`bulma` setup.
But as builds tool go, what does Next provide, which Parcel (being like 1000000 times faster and easier to setup) doesn't?

I don't even want to argue, mostly to have those reasons in writing for the potential future devs to be aware.

**Comment by niklasp** [comment]
@kirushik thanks for your comment. I myself have no too specific reason for choosing next.js just very limited time atm :) I chose it because it offers painless building without any configuration needed (i thought). Then it turned out that organizations have to pay for pro when aiming for automatic builds and domain connection. thats why i quickly setup github pages because we didnt want to spend money for hosting at the moment. I just removed the automatic vercel build.

that said, i am happy when the build works in cloudflare. We could also just host the `master` branch on github pages and have other branches previews somewhere else. I do not care.

We agreed (with Jay) that a working version should be delivered before christmas (almost achieved) and we can of course figure out a perfect build pipeline with the upcoming iterations i would say. I am also open for moving to parcel, it was just too much overhead for me at the time i started building.

I am off for christmas now but will continue before new year.

**Comment by kirushik** [comment]
> that said, i am happy when the build works in cloudflare. We could also just host the `master` branch on github pages and have other branches previews somewhere else. I do not care.

If you'd just update the `yarn build` behaviour in `package.json` to work with whatever build system you prefer (so it takes the project and emits all the compiled artifacts into the `/dist` subfolder) — Cloudflare would start working automatically.

Can you please do that when it comes to updating this PR, and remove all other CI from this branch?
Don't mind reintroduction of things like Github Actions when it would be time for us to unit-test the codebase; but for now simpler is better, and CF Pages have an added bonus of already working (both to host `master` at https://stake-n-vote.pages.dev/, and branch-specific subdomains like https://frontend.stake-n-vote.pages.dev/ for the `frontend` branch from the #4. There would be https://beta.stake-n-vote.pages.dev/ for this PR as soon as the `yarn build` is fixed and the fix is pushed.)

**Comment by niklasp** [comment]
as far as i can tell my setup is correct now, build succeeds (https://github.com/TheKusamarian/stake-n-vote/runs/20029589695) to the `dist/` subfolder, but https://beta.stake-n-vote.pages.dev/ shows a white page and many errors
Bildschirmfoto 2023-12-29 um 16 44 53. 
Strange error, somehow headers (mime type settings) seem wrong (server issue?). Can you check the cloudflare settings and see if you can make it work from the admin dashboard in cloudflare. 

Also I cannot see logs in cloudflare, clicking the link tells me I have no project configured with that name (probable need access rights?)

Any help is appreciated so we can get the site online asap.

(ill remove all other ci as soon as cloudflare works)

**Comment by kirushik** [comment]
@niklasp your build system config adds an extra `/stake-n-vote` path element to your routes in prod (see next.config.js, line 3).
This is why all your routes are 404 pages, and cannot be executed as javascript.

Please remove that line (sorry for not doing it myself, but I'm from my phone right now) — and it should work 🤞

**Comment by niklasp** [comment]
Thanks for looking and finding the issue. Build works now and I removed the other CI.

Can you also connect with @JayChrawnna concerning the connection of the `thekus.xyz` domain as soon as you are ready?

(on the same note, i tried to login to cloudflare by connecting my profile / theKusamarian but it doesnt work, will i be able to see logs, change settings in case we need it?)

**Review by kirushik — APPROVED** [review]
LGTM

**Pull request merged**
